name: 网站健康检查

on:
  schedule:
    - cron: "*/1 * * * *"  # 每分钟运行一次
  workflow_dispatch:  # 添加这个以支持手动触发

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v4
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
      - name: Check jq version
        run: jq --version      
      - name: Debug Logs
        run: ls -lah logs/ && cat logs/report.json
